package tetris;

import javax.swing.JFrame;

// Main class for the Tetris game //

public class Tetris {

	public static void main(String[] args) {
		
		// gameWidth and gameHeight values are generated by trial and error //
		int leftBound = 0;
		int gameWidth = 600;
		int topBound = 0;
		int gameHeight = 740;
				
		JFrame obj = new JFrame();
		Gameplay gamePlay = new Gameplay();

		obj.setBounds(leftBound, topBound, gameWidth, gameHeight);
		
		obj.setLocationRelativeTo(null);
		
		obj.setTitle("Tetris");
		
		obj.setResizable(false);
		
		obj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		obj.add(gamePlay);
		
		obj.setVisible(true);

	}

}
